#!/usr/bin/env bash
# fetch-secrets.sh — Pull secrets from AWS SSM Parameter Store and write .env
#
# Usage:
#   ./scripts/fetch-secrets.sh [--project bot|dashboard] [--output /path/to/.env]
#
# Required IAM permissions (attach to EC2 instance profile):
#   ssm:GetParameter
#   ssm:GetParametersByPath
#   kms:Decrypt (if using SecureString with custom KMS key)
#
# SSM Parameter Store layout expected:
#   /megaeth/bot/RPC_URL                 (SecureString)
#   /megaeth/bot/PRIVATE_KEY             (SecureString)
#   /megaeth/bot/WORLD_EXCHANGE_ADDRESS  (String)
#   /megaeth/bot/WORLD_USDM_ADDRESS      (String)
#   /megaeth/bot/WALLET_ADDRESS           (String)
#   /megaeth/dashboard/HISTORY_API_KEY    (SecureString)
#   /megaeth/dashboard/RPC_URL            (SecureString)
#   /megaeth/dashboard/DASHBOARD_WALLET_ADDRESS (String)
#   /megaeth/dashboard/WORLD_EXCHANGE_ADDRESS   (String)
#
# Non-secret defaults (written directly, not fetched from SSM):
#   CHAIN_ID=4326
#   BRIDGE_HOST=127.0.0.1
#   BRIDGE_PORT=3000
#   BOT_DATA_DIR=/var/lib/megaeth-bot

set -euo pipefail

PROJECT="bot"
OUTPUT_FILE=""
AWS_REGION="${AWS_REGION:-us-east-1}"
AWS_PROFILE="${AWS_PROFILE:-}"
SSM_PREFIX="/megaeth"

# ── Parse arguments ──────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --project) PROJECT="$2"; shift 2 ;;
        --output)  OUTPUT_FILE="$2"; shift 2 ;;
        --region)  AWS_REGION="$2"; shift 2 ;;
        --profile) AWS_PROFILE="$2"; shift 2 ;;
        *)
            echo "Unknown argument: $1" >&2
            echo "Usage: $0 [--project bot|dashboard] [--output .env] [--region us-east-1] [--profile NAME]" >&2
            exit 2
            ;;
    esac
done

# ── Build AWS CLI profile argument ───────────────────────────────
AWS_PROFILE_ARG=()
if [[ -n "$AWS_PROFILE" ]]; then
    AWS_PROFILE_ARG=(--profile "$AWS_PROFILE")
fi

if [[ -z "$OUTPUT_FILE" ]]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    OUTPUT_FILE="$SCRIPT_DIR/../.env"
fi

# ── Fetch a parameter from SSM ───────────────────────────────────
# Usage: ssm_get <param-name> <env-var-name> [--required]
ssm_get() {
    local param_name="$1"
    local env_var="$2"
    local required="${3:-}"
    local full_name="$SSM_PREFIX/$PROJECT/$param_name"

    echo "  Fetching $full_name ..." >&2
    local value
    if value=$(aws ssm get-parameter \
        --region "$AWS_REGION" \
        "${AWS_PROFILE_ARG[@]}" \
        --name "$full_name" \
        --with-decryption \
        --query 'Parameter.Value' \
        --output text \
        2>/dev/null); then
        if [[ -n "$value" && "$value" != "None" ]]; then
            echo "${env_var}=${value}"
            return 0
        fi
    fi

    if [[ "$required" == "--required" ]]; then
        echo "ERROR: Required SSM parameter not found: $full_name" >&2
        echo "Ensure the parameter exists and the instance profile has ssm:GetParameter." >&2
        exit 1
    fi
    echo "# ${env_var} — NOT FOUND in SSM ($full_name)" >&2
    return 0
}

# ── Verify AWS access ────────────────────────────────────────────
if ! aws sts get-caller-identity --region "$AWS_REGION" "${AWS_PROFILE_ARG[@]}" &>/dev/null; then
    echo "ERROR: Cannot authenticate to AWS. Check instance profile/credentials. Try --profile if using SSO." >&2
    echo "Falling back to existing .env if present." >&2
    if [[ -f "$OUTPUT_FILE" ]]; then
        echo "Using existing $OUTPUT_FILE (NOT updated from SSM)." >&2
        exit 0
    fi
    exit 1
fi

echo "=== Fetching secrets from AWS SSM ($SSM_PREFIX/$PROJECT) ===" >&2

# ── Write .env header ────────────────────────────────────────────
cat > "$OUTPUT_FILE" << 'HEADER'
# ──────────────────────────────────────────────────────────────────
# Generated by fetch-secrets.sh from AWS SSM Parameter Store.
# DO NOT EDIT MANUALLY — changes will be overwritten on next fetch.
# Timestamp: TIMESTAMP_PLACEHOLDER
# ──────────────────────────────────────────────────────────────────
HEADER

# Replace placeholder with actual timestamp
# (avoiding date command in heredoc)
CURRENT_TS="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
if [[ "$(uname)" == "Darwin" ]]; then
    sed -i '' "s/TIMESTAMP_PLACEHOLDER/$CURRENT_TS/" "$OUTPUT_FILE"
else
    sed -i "s/TIMESTAMP_PLACEHOLDER/$CURRENT_TS/" "$OUTPUT_FILE"
fi

# ── Fetch per-project secrets ────────────────────────────────────
if [[ "$PROJECT" == "bot" ]]; then
    echo "# megaeth-bot secrets" >> "$OUTPUT_FILE"
    ssm_get "RPC_URL"              "RPC_URL"              --required >> "$OUTPUT_FILE"
    ssm_get "PRIVATE_KEY"           "PRIVATE_KEY"           --required >> "$OUTPUT_FILE"
    ssm_get "WORLD_EXCHANGE_ADDRESS" "WORLD_EXCHANGE_ADDRESS" --required >> "$OUTPUT_FILE"
    ssm_get "WORLD_USDM_ADDRESS"    "WORLD_USDM_ADDRESS"    --required >> "$OUTPUT_FILE"
    ssm_get "WALLET_ADDRESS"        "WALLET_ADDRESS"        --required >> "$OUTPUT_FILE"

    echo "" >> "$OUTPUT_FILE"
    echo "# Non-secret defaults" >> "$OUTPUT_FILE"
    echo "CHAIN_ID=4326" >> "$OUTPUT_FILE"
    echo "BRIDGE_HOST=127.0.0.1" >> "$OUTPUT_FILE"
    echo "BRIDGE_PORT=3000" >> "$OUTPUT_FILE"
    echo "BOT_DATA_DIR=${BOT_DATA_DIR:-/var/lib/megaeth-bot}" >> "$OUTPUT_FILE"

elif [[ "$PROJECT" == "dashboard" ]]; then
    echo "# megaeth-dashboard secrets" >> "$OUTPUT_FILE"
    ssm_get "HISTORY_API_KEY"            "HISTORY_API_KEY"            --required >> "$OUTPUT_FILE"
    ssm_get "RPC_URL"                    "RPC_URL"                    --required >> "$OUTPUT_FILE"
    ssm_get "DASHBOARD_WALLET_ADDRESS"   "DASHBOARD_WALLET_ADDRESS"   --required >> "$OUTPUT_FILE"
    ssm_get "WORLD_EXCHANGE_ADDRESS"     "WORLD_EXCHANGE_ADDRESS"     --required >> "$OUTPUT_FILE"

    echo "" >> "$OUTPUT_FILE"
    echo "# Non-secret defaults" >> "$OUTPUT_FILE"
    echo "CHAIN_ID=4326" >> "$OUTPUT_FILE"
    echo "POSITION_PORT=3001" >> "$OUTPUT_FILE"
    echo "REFRESH_SECONDS=5" >> "$OUTPUT_FILE"
    echo "HISTORY_LIMIT=10000" >> "$OUTPUT_FILE"
    echo "HISTORY_API_URL=\${HISTORY_API_URL:-http://52.3.225.23:8080/history}" >> "$OUTPUT_FILE"
    echo "POSITION_API_URL=http://127.0.0.1:3001" >> "$OUTPUT_FILE"

else
    echo "ERROR: Unknown project '$PROJECT'. Use 'bot' or 'dashboard'." >&2
    exit 1
fi

# ── Set restrictive permissions ──────────────────────────────────
chmod 600 "$OUTPUT_FILE"
echo "" >&2
echo "Secrets written to $OUTPUT_FILE ($(wc -l < "$OUTPUT_FILE") lines)." >&2
echo "Done." >&2
