#!/usr/bin/env bash
# Fetch secrets from AWS SSM Parameter Store for megaeth-dashboard.
#
# Usage:
#   ./fetch-secrets.sh --project dashboard [--region us-east-1] [--output .env] [--profile default]
#
# Parameters fetched:
#   /megaeth/dashboard/RPC_URL                 (SecureString)
#   /megaeth/dashboard/HISTORY_API_KEY          (SecureString)
#   /megaeth/dashboard/DASHBOARD_WALLET_ADDRESS (String)
#   /megaeth/dashboard/WORLD_EXCHANGE_ADDRESS   (String)
#
# Non-secret defaults written directly:
#   CHAIN_ID=4326
#   POSITION_PORT=3001
#   REFRESH_SECONDS=5
#   HISTORY_LIMIT=10000
#   HISTORY_API_URL=http://127.0.0.1:8080/history
#   POSITION_API_URL=http://127.0.0.1:3001
set -euo pipefail

PROJECT="dashboard"
REGION="us-east-1"
OUTPUT=""
PROFILE=""

usage() {
    cat << 'EOF'
Usage: fetch-secrets.sh --project <name> [--region <region>] [--output <path>] [--profile <profile>]

Fetch secrets from AWS SSM Parameter Store and write to .env.

Options:
  --project   Required. Project name (dashboard).
  --region    AWS region (default: us-east-1).
  --output    Output file path (default: <script-dir>/../.env).
  --profile   AWS CLI profile (optional).
EOF
    exit 1
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --project)  PROJECT="$2"; shift 2 ;;
        --region)   REGION="$2"; shift 2 ;;
        --output)   OUTPUT="$2"; shift 2 ;;
        --profile)  PROFILE="$2"; shift 2 ;;
        -h|--help)  usage ;;
        *)          echo "Unknown flag: $1"; usage ;;
    esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT="${OUTPUT:-$ROOT/.env}"

AWS_OPTS=(--region "$REGION")
[[ -n "$PROFILE" ]] && AWS_OPTS+=(--profile "$PROFILE")

ssm_get() {
    # Fetch one parameter; return value or empty string on failure.
    local name="$1"
    aws ssm get-parameter \
        --name "/megaeth/${PROJECT}/${name}" \
        --with-decryption \
        --query 'Parameter.Value' \
        --output text \
        "${AWS_OPTS[@]}" 2>/dev/null || true
}

# ── Verify AWS access ────────────────────────────────────────────
if ! aws sts get-caller-identity "${AWS_OPTS[@]}" &>/dev/null; then
    echo "ERROR: Cannot authenticate to AWS. Check credentials and profile." >&2
    exit 1
fi

# ── Fetch parameters ─────────────────────────────────────────────
echo "Fetching secrets from /megaeth/${PROJECT}/ ..."

RPC_URL=$(ssm_get "RPC_URL")
HISTORY_API_KEY=$(ssm_get "HISTORY_API_KEY")
DASHBOARD_WALLET_ADDRESS=$(ssm_get "DASHBOARD_WALLET_ADDRESS")
WORLD_EXCHANGE_ADDRESS=$(ssm_get "WORLD_EXCHANGE_ADDRESS")

# Allow overriding non-secret defaults from SSM
CHAIN_ID=$(ssm_get "CHAIN_ID")
POSITION_PORT=$(ssm_get "POSITION_PORT")
REFRESH_SECONDS=$(ssm_get "REFRESH_SECONDS")
HISTORY_LIMIT=$(ssm_get "HISTORY_LIMIT")
HISTORY_API_URL=$(ssm_get "HISTORY_API_URL")
POSITION_API_URL=$(ssm_get "POSITION_API_URL")

# ── Validate required secrets ────────────────────────────────────
MISSING=""
[[ -z "$RPC_URL" ]]                  && MISSING+="  RPC_URL\n"
[[ -z "$HISTORY_API_KEY" ]]          && MISSING+="  HISTORY_API_KEY\n"
[[ -z "$DASHBOARD_WALLET_ADDRESS" ]] && MISSING+="  DASHBOARD_WALLET_ADDRESS\n"
[[ -z "$WORLD_EXCHANGE_ADDRESS" ]]   && MISSING+="  WORLD_EXCHANGE_ADDRESS\n"

if [[ -n "$MISSING" ]]; then
    echo "ERROR: Missing required SSM parameters:" >&2
    echo -e "$MISSING" >&2
    echo "Create them under /megaeth/${PROJECT}/ with:" >&2
    echo "  aws ssm put-parameter --name /megaeth/${PROJECT}/<key> --type SecureString --value <value> ${AWS_OPTS[*]}" >&2
    exit 1
fi

# ── Apply non-secret defaults ────────────────────────────────────
CHAIN_ID="${CHAIN_ID:-4326}"
POSITION_PORT="${POSITION_PORT:-3001}"
REFRESH_SECONDS="${REFRESH_SECONDS:-5}"
HISTORY_LIMIT="${HISTORY_LIMIT:-10000}"
HISTORY_API_URL="${HISTORY_API_URL:-http://127.0.0.1:8080/history}"
POSITION_API_URL="${POSITION_API_URL:-http://127.0.0.1:3001}"

# ── Write .env ───────────────────────────────────────────────────
cat > "$OUTPUT" << EOF
# Generated by fetch-secrets.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT EDIT MANUALLY — regenerated on every service start.
# Source: AWS SSM Parameter Store /megaeth/${PROJECT}/

# ── Secrets (SSM) ────────────────────────────────────────────────
RPC_URL=${RPC_URL}
HISTORY_API_KEY=${HISTORY_API_KEY}
DASHBOARD_WALLET_ADDRESS=${DASHBOARD_WALLET_ADDRESS}
WORLD_EXCHANGE_ADDRESS=${WORLD_EXCHANGE_ADDRESS}

# ── Non-secret defaults (override via SSM) ───────────────────────
CHAIN_ID=${CHAIN_ID}
POSITION_PORT=${POSITION_PORT}
REFRESH_SECONDS=${REFRESH_SECONDS}
HISTORY_LIMIT=${HISTORY_LIMIT}
HISTORY_API_URL=${HISTORY_API_URL}
POSITION_API_URL=${POSITION_API_URL}
EOF

chmod 600 "$OUTPUT"
echo "Secrets written to $OUTPUT"
