#!/usr/bin/env bash
# SSL certificate setup for megaeth-dashboard.
#
# Two modes:
#   Self-signed (default):   ./setup-ssl.sh
#   Let's Encrypt (domain):  ./setup-ssl.sh --domain dashboard.example.com --email admin@example.com
#
# Self-signed certs are generated by ec2-userdata.sh during bootstrap.
# Run this script to replace them with Let's Encrypt certificates
# after DNS is pointed at the instance.
set -euo pipefail

DOMAIN=""
EMAIL=""
MODE="selfsigned"

usage() {
    cat << 'EOF'
Usage: setup-ssl.sh [--domain <fqdn>] [--email <email>]

Options:
  --domain   Domain name (required for Let's Encrypt).
  --email    Email for Let's Encrypt notifications (required for Let's Encrypt).
  -h, --help Show this help.

Without --domain, generates a new self-signed certificate.
EOF
    exit 1
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --domain) DOMAIN="$2"; shift 2 ;;
        --email)  EMAIL="$2"; shift 2 ;;
        -h|--help) usage ;;
        *)        echo "Unknown flag: $1"; usage ;;
    esac
done

SSL_DIR="/etc/nginx/ssl"
CERT_FILE="$SSL_DIR/dashboard.crt"
KEY_FILE="$SSL_DIR/dashboard.key"

mkdir -p "$SSL_DIR"

# ── Let's Encrypt path ────────────────────────────────────────────
if [[ -n "$DOMAIN" ]]; then
    if [[ -z "$EMAIL" ]]; then
        echo "ERROR: --email is required for Let's Encrypt." >&2
        exit 1
    fi

    # Install certbot if not present
    if ! command -v certbot &>/dev/null; then
        echo "Installing certbot..."
        dnf install -y certbot python3-certbot-nginx
    fi

    echo "Requesting Let's Encrypt certificate for $DOMAIN ..."
    certbot certonly \
        --nginx \
        --non-interactive \
        --agree-tos \
        --email "$EMAIL" \
        --domain "$DOMAIN" \
        --keep-until-expiring \
        --expand

    # Symlink certbot certs into nginx ssl dir
    ln -sf "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" "$CERT_FILE"
    ln -sf "/etc/letsencrypt/live/$DOMAIN/privkey.pem"   "$KEY_FILE"
    chmod 600 "$KEY_FILE"

    # Add auto-renewal cron
    cat > /etc/cron.daily/certbot-renew << 'CRONEOF'
#!/bin/bash
certbot renew --quiet --nginx
systemctl reload nginx
CRONEOF
    chmod +x /etc/cron.daily/certbot-renew

    systemctl reload nginx
    echo "Let's Encrypt certificate installed for $DOMAIN."
    echo "Auto-renewal cron job created at /etc/cron.daily/certbot-renew"

# ── Self-signed path ─────────────────────────────────────────────
else
    PUBLIC_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || echo "127.0.0.1")

    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout "$KEY_FILE" \
        -out "$CERT_FILE" \
        -subj "/CN=${PUBLIC_IP}/O=MegaETH/C=US" \
        -addext "subjectAltName=IP:${PUBLIC_IP}"

    chmod 600 "$KEY_FILE"
    systemctl reload nginx
    echo "Self-signed certificate generated for IP ${PUBLIC_IP}."
    echo "WARNING: Self-signed certs trigger browser warnings."
    echo "Run with --domain and --email for a trusted Let's Encrypt certificate."
fi
